name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download UiPath CLI (specific version from Azure DevOps)
        run: |
          curl -L -o uipcli.zip "https://uipath.pkgs.visualstudio.com/Public.Feeds/_apis/packaging/feeds/1c781268-d43d-45ab-9dfc-0151a1c740b7/nuget/packages/UiPath.CLI/versions/25.4.9239.19674"
          unzip -o uipcli.zip -d uipcli
          chmod +x ./uipcli/tools/uipcli.dll

      - name: Verify uipcli.exe exists
        run: |
          if [ -f "./uipcli/tools/uipcli.exe" ]; then
            echo "✅ uipcli.exe found at ./uipcli/tools/uipcli.exe"
          else
            echo "❌ uipcli.exe not found at ./uipcli/tools/uipcli.exe"
          fi
