name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download UiPath CLI from GitHub Release
        run: |
         curl -L -o uipcli.zip "https://github.com/Balamanikanta1210/Cross_Platform/releases/download/1.0.0/UiPath.CLI.25.4.9239.19674.zip"
         unzip -o uipcli.zip -d uipcli
         chmod +x ./uipcli/tools/uipcli.dll

      - name: Verify uipcli.exe exists
        run: |
          if [ -f "./uipcli/tools/uipcli.exe" ]; then
            echo "✅ uipcli.exe found at ./uipcli/tools/uipcli.exe"
          else
            echo "❌ uipcli.exe not found at ./uipcli/tools/uipcli.exe"
          fi
      - name: Run uipcli pack
        run: |
         projectPath="$GITHUB_WORKSPACE/project.json"
         outputPath="$GITHUB_WORKSPACE/Output"

         echo "Project path: $projectPath"
         echo "Output path: $outputPath"

         applicationId="${{ secrets.UIPATH_APPLICATION_ID }}"
         applicationSecret="${{ secrets.UIPATH_APPLICATION_SECRET }}"

         dotnet ./uipcli/tools/uipcli.dll package pack "$projectPath" \
         -o "$outputPath" \
         --libraryOrchestratorUrl "https://cloud.uipath.com/" \
         --libraryOrchestratorTenant "DefaultTenant" \
         --libraryOrchestratorApplicationId "$applicationId" \
         --libraryOrchestratorApplicationSecret "$applicationSecret" \
         --libraryOrchestratorApplicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users.Read" \
         --libraryOrchestratorAccountForApp "walmazwnmqbk"
      - name: Run uipcli deploy
        run: |
          echo "Deploying package: $outputPath"
          ls -l "$packagePath"
          applicationId="${{ secrets.UIPATH_APPLICATION_ID }}"
          applicationSecret="${{ secrets.UIPATH_APPLICATION_SECRET }}"
          
          dotnet ./uipcli/tools/uipcli.dll package deploy "$outputPath" \
          "https://cloud.uipath.com" \
          "DefaultTenant" \
          --accountForApp "walmazwnmqbk" \
          --applicationId "$applicationId" \
          --applicationSecret  "$applicationSecret" \
          --applicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users.Read" \
          --organizationUnit  "Test" \
          --traceLevel Verbose
